### ISSUE TITLE
create_image vs create_devami

### ISSUE THREAD

**Issue by jeromelecoq** [cunningham-lab/neurocaas#10]
Hi,
I am reviewing the ami creation process in the dev doc file 
and it states to use the cmd 
devami.create_image(name)

to finalize your AMI. 

I am also looking at the python code and I can see that the function in NeuroCAASAMI
is called :
devami.create_devami(name)

could there be a typo?

**Comment by cellistigs** [comment]
Hi Jerome, 

You are correct! That is a typo, thank you for the catch. I'm updating now!

**Comment by cellistigs** [comment]
Updated. Thank you!
