### ISSUE TITLE
setting up aws credentials

### ISSUE THREAD

**Issue by bendichter** [cunningham-lab/neurocaas#133]
I am attempting to use the CLI to work directly with the DANDI Archive (related to #132). I am trying to follow the instructions [here](https://neurocaas.readthedocs.io/en/latest/user/cli.html#installation) for setting up the CLI. 

First of all, it is not clear to me from these instructions how I am supposed to configure the aws cli. I guess I am supposed to run `aws configure`, so I do that. I get:

AWS Access Key ID [None]:
AWS Secret Access Key [None]:
Default region name [None]: 
Default output format [None]: 

I copy/pasted the AWS Access Key ID and AWS Secret Access Key from http://www.neurocaas.org/profile/ and left the other two blank. Then I ran `aws s3 ls` and get 

`
An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS Access Key Id you provided does not exist in our records.
`

**Comment by cellistigs** [comment]
Thanks for bringing this to our attention. First, that configuration step is correct, and we can make that clearer. 
Second, can you provide the email address you used to sign up for NeuroCAAS? We can check your account from our side.

**Comment by bendichter** [comment]
Thanks for looking into this, @cellistigs!

ben.dichter@catalystneuro.com

**Comment by bendichter** [comment]
I did a bit of digging to see if  I could solve this on my own. 
 I tried: 

```bash
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
```

as recommended by [this stackoverflow post](https://stackoverflow.com/questions/39051477/the-aws-access-key-id-does-not-exist-in-our-records) but it did not fix it. I also deleted ~/.aws/config and confirmed ~/.aws/credentials was correct

**Comment by cellistigs** [comment]
I've taken a look at your AWS credentials, and it looks like there was a potential issue with a migration of our user management system since you signed up. Additionally, as a user you may not have permission to list all buckets in our account. 

I have reset your AWS credentials as located on the NeuroCAAS website. Can you please reconfigure your CLI, and run the following command: 
```
aws s3 ls s3://dlc-ncap-web
```

And please let me know if that's successful.

**Comment by cellistigs** [comment]
Closing this following update from our meeting.
