### ISSUE TITLE
neurocaas fails if AMI lacks RootDeviceName, but RootDeviceName is optional

### ISSUE THREAD

**Issue by jacksonloper** [cunningham-lab/neurocaas#15]
I think sometimes AMI's dont actually have a RootDeviceName -- according to https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RegisterImage.html it is not required.  So then that throws an error when computing volume size.

Need to figure out how to compute volume size without using RootDeviceName from the AMI.

**Comment by cellistigs** [comment]
RegisterImage requests part of an Amazon Machine Image configuration to create a new image, and providing a root device name is indeed optional for that process. However, when describing existing images, a root device should always exist. It's possible that this error is thrown when we request a new instance from an image that is still being registered- I'll open a new issue to investigate that further.
