### ISSUE TITLE
No RootDeviceName on AMI

### ISSUE THREAD

**Issue by cellistigs** [cunningham-lab/neurocaas#16]
Occasionally, NeuroCAAS will complain with a KeyError that there is no RootDeviceName when creating instances from existing AMIs. This is most likely due to the AMI still being registered when a new instance creation request is submitted- investigate this further. 

See the following certificate from Shuonan running bardensr: 
REQUEST START TIME: 2020-07-21 00:11:20.91 (GMT)	 [+0:00:00.00]
ANALYSIS VERSION ID: 7444a38627c660bd6e93d5ab0a45a73c563eddb4	 [+0:00:00.12]
JOB ID: 07_20_test_4	 [+0:00:00.17]
[Job Manager] Detected new job: starting up.	 [+0:00:00.25]
        [Internal (init)] Initializing job manager.	 [+0:00:00.29]
        [Internal (init)] Analysis request with dataset(s): debuggers/inputs/data_2.hdf5, config file debuggers/configs/config_2.yaml	 [+0:00:00.36]
[Job Manager] STEP 1/4 (Initialization): DONE	 [+0:00:00.41]
        [Internal (get_costmonitoring)] Incurred cost so far: $0.6018133333333333. Remaining budget: $299.3981866666667	 [+0:00:01.19]
[Job Manager] STEP 2/4 (Validation): DONE	 [+0:00:01.27]
        [Internal (parse_config)] parameter __duration__ not given, proceeding with standard compute launch.	 [+0:00:01.43]
        [Internal (parse_config)] parameter __dataset_size__ is not given, proceeding with standard storage.	 [+0:00:01.49]
[Job Manager] STEP 3/4 (Environment Setup): INTERNAL ERROR. Traceback (most recent call last):
  File "/var/task/submit_start.py", line 717, in process_upload_dev
    submission.compute_volumesize()
  File "/var/task/submit_start.py", line 386, in compute_volumesize
    default_size = utilsparamec2.get_volumesize(os.environ["AMI"])
  File "/var/task/utilsparam/ec2.py", line 266, in get_volumesize
    root = response["Images"][0]["RootDeviceName"]
KeyError: 'RootDeviceName'
[Job Manager] Shutting down job.	 [+0:00:01.78]

**Comment by ShuonanChen** [comment]
Giving some extra time between updating the blueprint (`update_blueprint`) and terminating the instance (`terminate_devinstance`), and between terminating the instance and deploying the blue print (`bash iac_utils/fulldeploy.sh`) helped resolve this issue!

**Comment by cellistigs** [comment]
Great. I will add a wait time that checks for a successfully created AMI, and close this issue when that is complete.
