### ISSUE TITLE
problem signing up for alpha

### ISSUE THREAD

**Issue by bendichter** [cunningham-lab/neurocaas#45]
![image](https://user-images.githubusercontent.com/844306/105370407-8dc93b80-5bd1-11eb-8d77-a90235594acc.png)

**Comment by cellistigs** [comment]
Checking up on this now, thank you!

**Comment by cellistigs** [comment]
Currently augmenting our server to handle more users.

**Comment by cellistigs** [comment]
We should be all set with this now. Please go ahead and try signing up again!
