### ISSUE TITLE
Developer docs installation command pip install ./ncap_iac

### ISSUE THREAD

**Issue by apasarkar** [cunningham-lab/neurocaas#81]
To install the neurocaas source repo, the developer docs (at neurocaas/docs/source/develop/installation.rst) tell us to do the following: 
(1) conda activate neurocaas
(2) cd path/to/your/neurocaas
(3) pip install ./ncap_iac

I believe line (3) should instead be "pip install ." instead of "pip install ./ncap_iac"

**Comment by cellistigs** [comment]
Thanks Amol! This is now fixed as of commit 0ed7ecc26f1af4c79e5e80cd04acc2841a343240.
