### ISSUE TITLE
Environment to create when following installation procedure

### ISSUE THREAD

**Issue by jeromelecoq** [cunningham-lab/neurocaas#9]
Hi, 
This is Jerome from the Allen Institute. 

I appreciate this is coming a little unexpected and you are working hard to release NeuroCaas. 
I am very interested in this effort so I was going through your PDF installation to understand how it all will work to deploy an algorithm (I have a very good candidate for this). Most of it went smoothly except when I reached

"4 Initializing a blueprint"

This script bash iac_utils/configure.sh, expect that this environment : 
"source activate sam" was already set up. Unless I missed it I could not find it in the instruction. 

You might be aware of this already but in case you are not I thought this could be helpful. 

I thought that replacing 
"source activate sam" 
with 
"source activate neurocaas"

would work given the previous steps.
 
Happy to help more if I can. 

Jerome

**Comment by cellistigs** [comment]
Hi Jerome, 

Thank you for this comment! You are indeed correct, I will go in and enforce changes to that script to match what is given in the guide. Please let me know if you have any more issues with the installation document!

**Comment by cellistigs** [comment]
Hi Jerome, 

I have updated the scripts that you mentioned, and additionally the developer documentation. Thank you for your feedback, please let me know if you run into any other issues, or would like to contribute to the code!
